server {
    listen 80;
    
    # Habilita compressão gzip para melhor performance
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        
        # Desativa o cache do index.html para garantir que a versão mais recente e os novos assets sejam carregados
        add_header Cache-Control "no-store, no-cache, must-revalidate, proxy-revalidate, max-age=0";
        add_header Pragma "no-cache";
        add_header Expires 0;
        
        try_files $uri $uri/ /index.html;
    }
}
